services:
  bot_1:
    container_name: chrp_1
    build:
      context: https://github.com/2infinity-gh/hb.git#master
    volumes:
      - ./credentials/master_account:/home/hummingbot/conf
      - ./credentials/master_account/connectors:/home/hummingbot/conf/connectors
      - ./instances/chrp_1/logs:/home/hummingbot/logs
      - ./instances/chrp_1/data:/home/hummingbot/data
      - ./conf/scripts:/home/hummingbot/conf/scripts
      - ./conf/controllers:/home/hummingbot/conf/controllers
    environment:
      - CONFIG_PASSWORD=a
#      - CONFIG_FILE_NAME=v2_generic_with_controllers.py
#      - SCRIPT_CONFIG=conf_v2_generic_with_controllers_1.yml
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: 5
    tty: true
    stdin_open: true
  bot_2:
    container_name: chrp_2
    build:
      context: https://github.com/2infinity-gh/hb.git#master
    volumes:
      - ./credentials/master_account:/home/hummingbot/conf
      - ./credentials/master_account/connectors:/home/hummingbot/conf/connectors
      - ./instances/chrp_2/logs:/home/hummingbot/logs
      - ./instances/chrp_2/data:/home/hummingbot/data
      - ./conf/scripts:/home/hummingbot/conf/scripts
      - ./conf/controllers:/home/hummingbot/conf/controllers
    environment:
      - CONFIG_PASSWORD=a
#      - CONFIG_FILE_NAME=v2_generic_with_controllers.py
#      - SCRIPT_CONFIG=conf_v2_generic_with_contorllers_2.yml
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: 5
    tty: true
    stdin_open: true
  bot_3:
    container_name: chrp_3
    build:
      context: https://github.com/2infinity-gh/hb.git#master
    volumes:    
      - ./credentials/master_account:/home/hummingbot/conf
      - ./credentials/master_account/connectors:/home/hummingbot/conf/connectors
      - ./instances/chrp_3/logs:/home/hummingbot/logs
      - ./instances/chrp_3/data:/home/hummingbot/data
      - ./conf/scripts:/home/hummingbot/conf/scripts
      - ./conf/controllers:/home/hummingbot/conf/controllers
    environment:
      - CONFIG_PASSWORD=a
#      - CONFIG_FILE_NAME=v2_generic_with_controllers.py
#      - SCRIPT_CONFIG=conf_v2_generic_with_contorllers_2.yml
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: 5
    tty: true
    stdin_open: true
