version: "3.9"
services:
  bot:
    image: hummingbot/hummingbot:latest
    # image: hummingbot/hummingbot:latest-arm
    volumes:
      - "./hummingbot_files/conf:/conf"
      - "./hummingbot_files/conf/connectors:/conf/connectors"
      - "./hummingbot_files/conf/strategies:/conf/strategies"
      - "./hummingbot_files/logs:/logs"
      - "./hummingbot_files/data:/data"
      - "./hummingbot_files/scripts:/scripts"
      - "./hummingbot_files/certs:/certs"
    # environment:
      # - CONFIG_PASSWORD=[password]
      # - CONFIG_FILE_NAME=simple_pmm_example.py
      # - CONFIG_FILE_NAME=conf_pure_mm_1.yml
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: 5
    tty: true
    stdin_open: true
    network_mode: host
